// Static image imports (src/lib/images.ts) need Next's module declarations
// for .webp/.jpg/.png. Those normally arrive through next-env.d.ts, but
// that file is gitignored and generated by `next build`, and CI runs the
// typecheck before the build: on a fresh checkout every image import was
// "Cannot find module". Referencing them here makes the typecheck stand
// on its own.
/// <reference types="next/image-types/global" />
